//! Core persisted and runtime entity types.
use serde::{Deserialize, Serialize};
use serde_json::Value;
use utoipa::ToSchema;

/// Stored entity wrapper used by repository implementations.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct StoredDocument {
    /// Tenant owning this entity.
    pub tenant: String,
    /// Logical NGSI-LD entity id.
    #[serde(rename = "id")]
    pub ngsi_id: String,
    /// Raw NGSI-LD entity payload.
    #[serde(rename = "doc")]
    pub doc: Value,
}

/// Stored temporal entity wrapper with current snapshot and history.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct TemporalEntityDocument {
    /// Tenant owning this temporal entity.
    pub tenant: String,
    /// Logical NGSI-LD entity id.
    #[serde(rename = "id")]
    pub ngsi_id: String,
    /// Latest entity snapshot.
    #[serde(rename = "doc")]
    pub doc: Value,
    /// Flattened temporal attribute history.
    #[serde(default)]
    pub history: Vec<TemporalAttributeRecord>,
}

/// One stored temporal attribute instance.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct TemporalAttributeRecord {
    /// Attribute name this record belongs to.
    #[serde(rename = "attrId")]
    pub attr_id: String,
    /// Stable instance identifier for one temporal observation.
    #[serde(rename = "instanceId")]
    pub instance_id: String,
    #[serde(rename = "observedAt", skip_serializing_if = "Option::is_none")]
    pub observed_at: Option<String>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "modifiedAt", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    #[serde(rename = "deletedAt", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
    /// Attribute payload captured for this instance.
    pub value: Value,
}

/// Stored subscription wrapper used by repository implementations.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct SubscriptionDocument {
    /// Tenant owning this subscription.
    pub tenant: String,
    /// Logical subscription id.
    #[serde(rename = "id")]
    pub ngsi_id: String,
    /// Raw NGSI-LD subscription payload.
    #[serde(rename = "doc")]
    pub doc: Value,
}

/// Operation stored in replicated entity mutation log.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum EntityMutationOperation {
    /// Entity was created.
    Created,
    /// Entity was updated.
    Updated,
    /// Entity was deleted.
    Deleted,
}

impl EntityMutationOperation {
    /// Returns stable string stored in DefraDB mutation records.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Updated => "updated",
            Self::Deleted => "deleted",
        }
    }

    /// Parses stored operation string into typed operation.
    pub fn from_str(value: &str) -> Option<Self> {
        match value {
            "created" => Some(Self::Created),
            "updated" => Some(Self::Updated),
            "deleted" => Some(Self::Deleted),
            _ => None,
        }
    }
}

/// Replicated mutation-log record used for low-latency cross-node notifications.
///
/// Broker write paths append one record after successful entity persistence.
/// Other brokers poll this small log frequently, dedupe by `event_id`, skip
/// self-origin events, and deliver local subscriptions using `payload` plus
/// `changed_attributes`.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct EntityMutationDocument {
    /// Tenant owning mutated entity.
    pub tenant: String,
    /// Globally unique event id generated by origin broker.
    pub event_id: String,
    /// Logical NGSI-LD entity id.
    pub entity_id: String,
    /// Mutation operation.
    pub operation: EntityMutationOperation,
    /// Entity payload used for notification matching and delivery.
    pub payload: Value,
    /// Top-level attributes changed by this mutation.
    pub changed_attributes: Vec<String>,
    /// Broker id that originated this event.
    pub origin_broker_id: String,
    /// Origin timestamp in milliseconds since epoch.
    pub created_at_millis: i64,
}

/// Broker identity payload returned by `/info/sourceIdentity`.
#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct ContextSourceIdentity {
    pub id: String,
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(rename = "contextSourceAlias")]
    pub context_source_alias: String,
    #[serde(rename = "contextSourceUpTime")]
    pub context_source_up_time: String,
    #[serde(rename = "contextSourceTimeAt")]
    pub context_source_time_at: String,
}

/// Lifecycle event kind emitted after entity mutations.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EntityEventKind {
    /// Entity was created.
    Created,
    /// Entity was updated.
    Updated,
    /// Entity was deleted.
    Deleted,
}

/// Entity lifecycle event passed to notification matching code.
#[derive(Clone, Debug)]
pub struct EntityEvent {
    /// Event category.
    pub kind: EntityEventKind,
    /// Top-level attributes that changed for this event.
    pub changed_attributes: Vec<String>,
}
